class pont
camillacorreia/hangmanGame pull request #7
Opened 2022-11-12 21:26 UTC by StefaneOlliveira

2022-11-13 02:10 UTC, camillacorreia requested changes

2022-11-13 02:10 UTC, camillacorreia commented on classes/pontuacao.py
> +class Pontuacao:
Como estamos seguindo o padrão de escrita em inglês, o nome da classe pode ser Score, o que acha?

2022-11-13 02:10 UTC, camillacorreia commented on classes/pontuacao.py
> +        self.LetrasCertas = []
`rightLetters`

2022-11-13 02:10 UTC, camillacorreia commented on classes/word.py
> +      self.pontuacao.CalculaPont(self.e,self.correctWord,key)
`CalculateScore`

2022-11-13 02:10 UTC, camillacorreia commented on classes/word.py
> +    self.e = 0
Isso faz o quê?

2022-11-13 02:10 UTC, camillacorreia commented on classes/pontuacao.py
> +            self.contErros = self.contErros + 1
`countErrors`

2022-11-13 02:10 UTC, camillacorreia commented on classes/pontuacao.py
> +            self.contErros = self.contErros + 1
`errors`

2022-11-13 02:10 UTC, camillacorreia commented on classes/pontuacao.py
> +            self.contErros = self.contErros + 1
`hits`

2022-11-13 03:35 UTC, StefaneOlliveira commented on classes/pontuacao.py
> +class Pontuacao:
Pode ser, vou fazer as alterações.

2022-11-13 03:36 UTC, StefaneOlliveira commented on classes/word.py
> +    self.e = 0
Tem basicamente a mesma função da variável wrong, mas ela precisa ficar dentro dos dois if's para não contar o mesmo erro mais de uma vez.

2022-11-13 14:51 UTC, LucasLima337 commented on classes/score.py
> +
```suggestion

```

2022-11-13 14:51 UTC, LucasLima337 commented on classes/score.py
> +
```suggestion

```

2022-11-13 14:52 UTC, LucasLima337 commented on classes/score.py
> +
```suggestion
    
```

2022-11-13 14:52 UTC, LucasLima337 commented on classes/score.py
> +
```suggestion
```

2022-11-13 14:53 UTC, LucasLima337 commented on classes/score.py
> +
```suggestion
```

2022-11-13 14:53 UTC, LucasLima337 commented on classes/word.py
> +
```suggestion
```

2022-11-13 14:54 UTC, LucasLima337 commented on classes/word.py
> +
```suggestion
```

2022-11-13 14:54 UTC, LucasLima337 commented on classes/word.py
> +
```suggestion
```

2022-11-13 14:54 UTC, LucasLima337 commented on classes/word.py
> +
```suggestion
```

2022-11-13 14:55 UTC, LucasLima337 commented on classes/word.py
> +
```suggestion
```

2022-11-13 14:56 UTC, LucasLima337 commented on classes/score.py
> +
```suggestion
```

2022-11-13 17:15 UTC, camillacorreia commented on classes/score.py
> +
`CalculateScore`

2022-11-13 19:46 UTC, camillacorreia commented on classes/word.py
> +    self.e = 0
Tentar mudar o nome dessa variável para algo que a gente entenda o que ela significa, faz parte das boas práticas de programação.

2022-11-13 19:47 UTC, camillacorreia commented on classes/word.py
> +    self.e = 0
`e` não diz muita coisa.

2022-11-13 20:31 UTC, StefaneOlliveira commented on classes/word.py
> +    self.e = 0
Isso já foi feito nas alterações que eu subi.

2022-11-16 12:59 UTC, camillacorreia approved these changes

2022-11-16 12:59 UTC, camillacorreia commented on classes/word.py
> +      self.score.CalculaScore(self.errors,self.correctWord,key)
`CalculateScore`

2022-11-22 01:53 UTC, merged